version: "1"
services:
  mymongo_1:
    image: "mongo"
    container_name: mongo
    ports:
      - '27017:27017'
  flask:
    build: .
    container_name: flask
    ports:
      - "5001:5001"
    volumes:
      - .:/code
    depends_on:
      - mymongo_1
